# Generated by Django 3.0.3 on 2021-03-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostVulnManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnName', models.CharField(max_length=1000, null=True)),
                ('urgent', models.CharField(max_length=1000, null=True)),
                ('assetId', models.CharField(max_length=1000, null=True)),
                ('assetPublicIP', models.CharField(max_length=1000, null=True)),
                ('assetPrivateIP', models.CharField(max_length=1000, null=True)),
                ('assetRemarks', models.CharField(max_length=1000, null=True)),
                ('firstFindTime', models.DateTimeField(max_length=100, null=True)),
                ('lastFindTime', models.DateTimeField(max_length=100, null=True)),
                ('vulnExplain', models.CharField(max_length=2000, null=True)),
                ('vulnStatus', models.CharField(max_length=1000, null=True)),
                ('repairCommand', models.CharField(max_length=1000, null=True)),
                ('CVEID', models.CharField(max_length=2000, null=True)),
                ('label', models.CharField(max_length=1000, null=True)),
                ('createTime', models.DateTimeField(max_length=100, null=True)),
                ('updateTime', models.DateTimeField(max_length=100, null=True)),
                ('createPeople', models.CharField(max_length=100, null=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
