# Generated by Django 3.0.3 on 2021-03-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CopartnershipManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=1000, null=True)),
                ('systemName', models.CharField(max_length=100, null=True)),
                ('IP', models.CharField(max_length=100, null=True)),
                ('domain', models.CharField(max_length=100, null=True)),
                ('portService', models.CharField(max_length=2000, null=True)),
                ('information', models.CharField(max_length=100, null=True)),
                ('isdesensitization', models.CharField(max_length=100, null=True)),
                ('securityPeopleNum', models.CharField(max_length=100, null=True)),
                ('testCycle', models.CharField(max_length=100, null=True)),
                ('userSize', models.CharField(max_length=100, null=True)),
                ('systemSize', models.CharField(max_length=100, null=True)),
                ('deployPoint', models.CharField(max_length=100, null=True)),
                ('securityTest', models.CharField(max_length=1000, null=True)),
                ('testResult', models.CharField(max_length=1000, null=True)),
                ('systemType', models.CharField(max_length=100, null=True)),
                ('defensivePower', models.CharField(max_length=100, null=True)),
                ('systemStatus', models.CharField(max_length=100, null=True)),
                ('accessURL', models.CharField(max_length=1000, null=True)),
                ('developmentCompany', models.CharField(max_length=1000, null=True)),
                ('extranetAccess', models.CharField(max_length=100, null=True)),
                ('businessPeople', models.CharField(max_length=100, null=True)),
                ('businessPhone', models.CharField(max_length=100, null=True)),
                ('DevelopPeople', models.CharField(max_length=100, null=True)),
                ('DevelopPhone', models.CharField(max_length=100, null=True)),
                ('systemCommon', models.CharField(max_length=2000, null=True)),
                ('systemDescribe', models.CharField(max_length=2000, null=True)),
                ('deployTime', models.CharField(max_length=200, null=True)),
                ('createTime', models.DateTimeField(max_length=100, null=True)),
                ('updateTime', models.DateTimeField(max_length=100, null=True)),
                ('createPeople', models.CharField(max_length=100, null=True)),
                ('systemUsername', models.CharField(max_length=100, null=True)),
                ('systemPassword', models.CharField(max_length=100, null=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
