# Generated by Django 3.0.3 on 2021-03-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewAddressName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newAddressName', models.CharField(max_length=1000, null=True)),
                ('newAddressIP', models.CharField(max_length=10000, null=True)),
                ('newAddressComment', models.CharField(max_length=1000, null=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewAddrgrpName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newAddrgrpName', models.CharField(max_length=1000, null=True)),
                ('newAddrgrpMember', models.CharField(max_length=1000, null=True)),
                ('newAddrgrpComment', models.CharField(max_length=1000, null=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewFireWallFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newFilePath', models.CharField(max_length=500, null=True)),
                ('newFileName', models.CharField(max_length=1000, null=True)),
                ('newFileData', models.CharField(max_length=1000, null=True)),
                ('newFileType', models.CharField(max_length=1000, null=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewPolicyManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newRuleId', models.CharField(max_length=1000, null=True)),
                ('newRuleName', models.CharField(max_length=1000, null=True)),
                ('newRuleSa', models.CharField(max_length=1000, null=True)),
                ('newRuleDa', models.CharField(max_length=1000, null=True)),
                ('newRuleIzone', models.CharField(max_length=1000, null=True)),
                ('newRuleOzone', models.CharField(max_length=1000, null=True)),
                ('newRuleService', models.CharField(max_length=1000, null=True)),
                ('newRuleOpentime', models.CharField(max_length=1000, null=True)),
                ('newRuleStatus', models.CharField(max_length=1000, null=True)),
                ('newRuleActive', models.CharField(max_length=1000, null=True)),
                ('newRuleComment', models.CharField(max_length=1000, null=True)),
                ('newRuleAccount', models.CharField(max_length=1000, null=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='NewServiceName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newServiceName', models.CharField(max_length=1000, null=True)),
                ('newServiceProtocol', models.CharField(max_length=1000, null=True)),
                ('newServiceComment', models.CharField(max_length=1000, null=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
