# Generated by Django 3.0.3 on 2021-03-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PenetrationTestOverhaulManage',
            fields=[
                ('overhaulId', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('testStyle', models.CharField(max_length=100, null=True)),
                ('systemName', models.CharField(max_length=100, null=True)),
                ('systemVersion', models.CharField(max_length=100, null=True)),
                ('functionNum', models.IntegerField(null=True)),
                ('functionList', models.CharField(max_length=100, null=True)),
                ('vulnNum', models.CharField(max_length=100, null=True)),
                ('vulnDetail', models.CharField(max_length=100, null=True)),
                ('overhaulContent', models.CharField(max_length=100, null=True)),
                ('developCompany', models.CharField(max_length=200, null=True)),
                ('applyName', models.CharField(max_length=200, null=True)),
                ('applyPhone', models.CharField(max_length=200, null=True)),
                ('projectBossName', models.CharField(max_length=200, null=True)),
                ('projectBossPhone', models.CharField(max_length=200, null=True)),
                ('functionTestName', models.CharField(max_length=200, null=True)),
                ('PenetrationTestName', models.CharField(max_length=200, null=True)),
                ('testUserName', models.CharField(max_length=200, null=True)),
                ('testPassword', models.CharField(max_length=200, null=True)),
                ('testURL', models.CharField(max_length=200, null=True)),
                ('functionReportPath', models.CharField(max_length=1000, null=True)),
                ('reportPath', models.CharField(max_length=1000, null=True)),
                ('recordPath', models.CharField(max_length=1000, null=True)),
                ('functionReportIsExist', models.CharField(max_length=1000, null=True)),
                ('reportIsExist', models.CharField(max_length=1000, null=True)),
                ('recordIsExist', models.CharField(max_length=1000, null=True)),
                ('testIsOK', models.CharField(max_length=1000, null=True)),
                ('applyTime', models.CharField(max_length=200, null=True)),
                ('testTime', models.CharField(max_length=200, null=True)),
                ('releaseTime', models.CharField(max_length=200, null=True)),
                ('createTime', models.DateTimeField(db_column='createTime', null=True)),
                ('updateTime', models.DateTimeField(db_column='updateTime', null=True)),
                ('updatePeople', models.CharField(max_length=200, null=True)),
                ('isDelete', models.CharField(max_length=100)),
            ],
        ),
    ]
