# Generated by Django 3.0 on 2020-02-15 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuTitle', models.CharField(max_length=25, unique=True, verbose_name='菜单标题')),
                ('menuIcon', models.CharField(max_length=50, verbose_name='菜单图标')),
                ('isDelete', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_menu', to='RBAC.Menu', verbose_name='父菜单')),
            ],
        ),
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PermissionName', models.CharField(max_length=50, unique=True, verbose_name='权限标题')),
                ('PermissionIsMenu', models.BooleanField(default=False, verbose_name='菜单显示')),
                ('PermissionUrl', models.CharField(max_length=128)),
                ('PermissionMenu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PermissionMenu', to='RBAC.Menu', verbose_name='权限菜单')),
            ],
        ),
        migrations.CreateModel(
            name='UserResetpasswd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserResetpasswdEmail', models.EmailField(max_length=254, verbose_name='申请邮箱')),
                ('urlarg', models.CharField(max_length=50, verbose_name='重置参数')),
                ('UserResetpasswdIsCheck', models.BooleanField(default=False, verbose_name='是否使用')),
                ('UserResetpasswdUpdatetime', models.DateField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleName', models.CharField(max_length=25, unique=True, verbose_name='角色名称')),
                ('rolePermissionMenu', models.ManyToManyField(related_name='rolePermissionMenu', to='RBAC.UserPermission', verbose_name='权限菜单')),
            ],
        ),
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userEmail', models.EmailField(max_length=254, verbose_name='申请邮箱')),
                ('userPhone', models.EmailField(max_length=254, verbose_name='申请手机')),
                ('userName', models.CharField(max_length=50, verbose_name='用户名')),
                ('userPasswd', models.CharField(default='qwe123!@#', max_length=100, verbose_name='用户密码')),
                ('userStatus', models.CharField(choices=[('0', '待审批'), ('1', '审批通过'), ('2', '审批拒绝')], default='0', max_length=50, verbose_name='审批状态')),
                ('userIsCheck', models.BooleanField(default=False, verbose_name='是否审批')),
                ('userIsUse', models.BooleanField(default=False, verbose_name='是否使用')),
                ('userStarttime', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('userUpdatetime', models.DateTimeField(auto_now=True, verbose_name='审批时间')),
                ('userActionUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='regist_for_actionuser', to=settings.AUTH_USER_MODEL)),
                ('userRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userRole', to='RBAC.UserRole', verbose_name='账号权限')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userPosition', models.CharField(max_length=50, verbose_name='职位名称')),
                ('userPhone', models.CharField(max_length=50, verbose_name='手机号码')),
                ('userDescription', models.TextField(verbose_name='用户简介')),
                ('userLoginErrorCount', models.IntegerField(default=0, verbose_name='错误登陆')),
                ('userLockTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='锁定时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userRole', models.ManyToManyField(related_name='user_role', to='RBAC.UserRole', verbose_name='所属角色')),
            ],
        ),
    ]
