# Generated by Django 3.0.3 on 2020-05-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBAC', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilePasswd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=500, null=True)),
                ('passwd', models.CharField(max_length=1000, null=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
