# Generated by Django 3.0.3 on 2020-05-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RBAC', '0002_mobilepasswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilepasswd',
            name='mobile',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='mobilepasswd',
            name='passwd',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
