# Generated by Django 3.0.3 on 2021-03-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressName', models.CharField(max_length=1000, null=True)),
                ('addressIP', models.CharField(max_length=10000, null=True)),
                ('addressComment', models.CharField(max_length=1000, null=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AddrgrpName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addrgrpName', models.CharField(max_length=1000, null=True)),
                ('addrgrpMember', models.CharField(max_length=1000, null=True)),
                ('addrgrpComment', models.CharField(max_length=1000, null=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FireWallFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filePath', models.CharField(max_length=500, null=True)),
                ('fileName', models.CharField(max_length=1000, null=True)),
                ('fileData', models.CharField(max_length=1000, null=True)),
                ('fileType', models.CharField(max_length=1000, null=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PolicyManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruleId', models.CharField(max_length=1000, null=True)),
                ('ruleName', models.CharField(max_length=1000, null=True)),
                ('ruleSa', models.CharField(max_length=1000, null=True)),
                ('ruleDa', models.CharField(max_length=1000, null=True)),
                ('ruleIzone', models.CharField(max_length=1000, null=True)),
                ('ruleOzone', models.CharField(max_length=1000, null=True)),
                ('ruleService', models.CharField(max_length=1000, null=True)),
                ('ruleOpentime', models.CharField(max_length=1000, null=True)),
                ('ruleStatus', models.CharField(max_length=1000, null=True)),
                ('ruleActive', models.CharField(max_length=1000, null=True)),
                ('ruleComment', models.CharField(max_length=1000, null=True)),
                ('ruleAccount', models.CharField(max_length=1000, null=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceName', models.CharField(max_length=1000, null=True)),
                ('serviceProtocol', models.CharField(max_length=1000, null=True)),
                ('serviceComment', models.CharField(max_length=1000, null=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
