# Generated by Django 3.0.3 on 2020-06-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CnvdManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnvdNumber', models.CharField(max_length=1000, null=True)),
                ('cveNumber', models.CharField(max_length=1000, null=True)),
                ('cveUrl', models.CharField(max_length=1000, null=True)),
                ('cnvdTitle', models.CharField(max_length=1000, null=True)),
                ('cnvdServerity', models.CharField(max_length=100, null=True)),
                ('cnvdProducts', models.TextField(max_length=65535, null=True)),
                ('cnvdIsEvent', models.CharField(max_length=1000, null=True)),
                ('cnvdSubmitTime', models.CharField(max_length=1000, null=True)),
                ('cnvdOpenTime', models.CharField(max_length=1000, null=True)),
                ('cnvdDiscovererName', models.CharField(max_length=1000, null=True)),
                ('cnvdReferenceLink', models.CharField(max_length=1000, null=True)),
                ('cnvdFormalWay', models.TextField(max_length=65535, null=True)),
                ('cnvdDescription', models.CharField(max_length=1000, null=True)),
                ('cnvdPatchName', models.CharField(max_length=1000, null=True)),
                ('cnvdPatchDescription', models.CharField(max_length=1000, null=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VulhubManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulhubName', models.CharField(max_length=100, null=True)),
                ('vulhubApp', models.CharField(max_length=100, null=True)),
                ('vulhubCVE', models.CharField(max_length=100, null=True)),
                ('vulhubPath', models.CharField(max_length=100, null=True)),
                ('vulhubOption', models.BooleanField(default=False, null=True)),
                ('vulhubdetail', models.CharField(max_length=500, null=True)),
                ('vulhubStatus', models.BooleanField(default=False, null=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VulnerabilityManage',
            fields=[
                ('vulnNoticeFileId', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('vulnNoticeFileName', models.CharField(max_length=100, null=True)),
                ('vulnDomain', models.CharField(max_length=200, null=True)),
                ('vulnSystemName', models.CharField(max_length=100, null=True)),
                ('vulnDepartmentName', models.CharField(max_length=100, null=True)),
                ('vulnType', models.CharField(max_length=100, null=True)),
                ('vulnLevel', models.CharField(max_length=100, null=True)),
                ('vulnCount', models.IntegerField(null=True)),
                ('vulnDetail', models.CharField(max_length=1000, null=True)),
                ('vulnDevelopCompany', models.CharField(max_length=200, null=True)),
                ('vulnIsNotice', models.CharField(max_length=100, null=True)),
                ('vulnIsFeedback', models.CharField(max_length=100, null=True)),
                ('vulnNoticeWordPath', models.CharField(max_length=1000, null=True)),
                ('vulnNoticePdfPath', models.CharField(max_length=1000, null=True)),
                ('vulnFeedbackPath', models.CharField(max_length=1000, null=True)),
                ('vulnRetestPath', models.CharField(max_length=1000, null=True)),
                ('vulnIsRetest', models.CharField(max_length=100, null=True)),
                ('vulnIsEepair', models.CharField(max_length=100, null=True)),
                ('vulnSpecialTime', models.CharField(max_length=100, null=True)),
                ('vulncreateTime', models.DateTimeField(db_column='createTime', null=True)),
                ('vulnupdateTime', models.DateTimeField(db_column='updateTime', null=True)),
                ('vulncreatePeople', models.CharField(max_length=100, null=True)),
                ('vulnupdatePeople', models.CharField(max_length=100, null=True)),
                ('isDelete', models.CharField(max_length=100)),
            ],
        ),
    ]
