# Generated by Django 3.0.3 on 2020-06-23 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VulnManage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vulnerabilitymanage',
            old_name='vulnDepartmentName',
            new_name='vulnContactsName',
        ),
        migrations.RenameField(
            model_name='vulnerabilitymanage',
            old_name='vulnSpecialTime',
            new_name='vulnTestName',
        ),
    ]
