# Generated by Django 3.0.3 on 2020-06-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VulnManage', '0002_auto_20200623_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vulnerabilitymanage',
            old_name='vulnContactsName',
            new_name='DevelopPeople',
        ),
        migrations.AddField(
            model_name='vulnerabilitymanage',
            name='businessPeople',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
