# Generated by Django 3.0.3 on 2021-03-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectNameManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=1000, null=True)),
                ('projectDesc', models.CharField(max_length=1000, null=True)),
                ('businessPeople', models.CharField(max_length=100, null=True)),
                ('businessPhone', models.CharField(max_length=100, null=True)),
                ('developPeople', models.CharField(max_length=100, null=True)),
                ('developPhone', models.CharField(max_length=100, null=True)),
                ('developmentCompany', models.CharField(max_length=1000, null=True)),
                ('common', models.CharField(max_length=2000, null=True)),
                ('createTime', models.DateTimeField(max_length=100, null=True)),
                ('updateTime', models.DateTimeField(max_length=100, null=True)),
                ('createPeople', models.CharField(max_length=100, null=True)),
                ('isDelete', models.BooleanField(default=False)),
            ],
        ),
    ]
